  exports.car = [
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      mode: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 2,
      year:"2019",
      url:"https://th.bing.com/th/id/OIP.xiVjCFSEG15E-gER7ksKgwHaE7?pid=ImgDet&w=2048&h=1365&rs=1",
      name: "BMW 3 Series",
      person: 4,
      type: "Gasoline",
      speed: 8.2,
      type: "Automatic",
      price: 350,
    },
    {
      id: 3,
      year:"2020",
      name: "Volkswagen T-Cross",
      url:"https://th.bing.com/th/id/OIP.TB-HmPPiGdLpoq0q-m3OugHaE8?pid=ImgDet&rs=1",
      person: 4,
      type: "Gasoline",
      speed: 5.3,
      type: "Automatic",
      price: 400,
    },
    {
      id: 4,
      year:"2020",
      name: "Cadillac Escalade",
      url:"https://th.bing.com/th/id/OIP.EjUk-qPDYgNrajSHoA1EOwHaEK?pid=ImgDet&rs=1",
      person: 4,
      type: "GAsoline",
      speed: 7.7,
      type: "Automatic",
      price: 620,
    },
    {
      id: 5,
      year:"2021",
      name: "BMW 4Series GTI",
      url:"https://th.bing.com/th/id/OIP.9NSK81Tzn1uHjaud_NsSjwHaEA?pid=ImgDet&rs=1",
      person: 4,
      type: "GAsoline",
      speed: 7.6,
      type: "Automatic",
      price: 530,
    },
    {
      id: 6,
      year:"2019",
      name: "BMW 4 Series",
      url:"https://th.bing.com/th/id/OIP.qh2W_F7vMWL_iJSXCtL68QHaEK?pid=ImgDet&rs=1",
      person: 4,
      type: "Gasoline",
      speed: 7.3,
      type: "Automatic",
      price: 490,
    },
    {
      id: 7,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 8,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 9,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 10,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 11,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 12,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 13,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      price: 440,
    },
    {
      id: 14,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 15,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 16,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 17,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 18,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 19,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 20,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 21,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 22,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 23,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 24,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 25,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 26,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 27,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 28,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 29,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 30,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 31,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 32,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 33,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 34,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 35,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 36,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 37,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 38,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 39,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 40,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 41,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 42,
      year:"2021",
      name: "Toyota RAV4",
      url:"https://tse2.mm.bing.net/th?id=OIP.KijQjIFBMlUe6NuVZQcTHAHaE6&pid=Api&P=0&h=220",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
    {
      id: 1,
      year:"2021",
      name: "Toyota RAV4",
      person: 4,
      type: "Hybrid",
      speed: 6.1,
      type: "Automatic",
      price: 440,
    },
  ];
